
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-05T09:19:10-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "99b85c35e8d2f7d97e47f438a1425030a91e13b3",
 "version": "1.82.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
