# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CosmosChosen',
                'doc_host': 'https://2catycm.github.io',
                'git_url': 'https://github.com/2catycm/CosmosChosen',
                'lib_path': 'CosmosChosen'},
  'syms': {'CosmosChosen.core': {'CosmosChosen.core.foo': ('core.html#foo', 'CosmosChosen/core.py')}}}
