from enum import Enum


class CreateApiTokenRequestRole(str, Enum):
    DEPLOYMENT_ADMIN = "DEPLOYMENT_ADMIN"
    ORGANIZATION_BILLING_ADMIN = "ORGANIZATION_BILLING_ADMIN"
    ORGANIZATION_MEMBER = "ORGANIZATION_MEMBER"
    ORGANIZATION_OWNER = "ORGANIZATION_OWNER"
    WORKSPACE_AUTHOR = "WORKSPACE_AUTHOR"
    WORKSPACE_MEMBER = "WORKSPACE_MEMBER"
    WORKSPACE_OPERATOR = "WORKSPACE_OPERATOR"
    WORKSPACE_OWNER = "WORKSPACE_OWNER"

    def __str__(self) -> str:
        return str(self.value)
