# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/terraquantum/bff/v1/bff/rtd_credentials.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'com/terraquantum/bff/v1/bff/rtd_credentials.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1com/terraquantum/bff/v1/bff/rtd_credentials.proto\x12\x1b\x63om.terraquantum.bff.v1.bff\"M\n\x13RtdCredentialsProto\x12\x1a\n\x08username\x18\x01 \x01(\tR\x08username\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08passwordB\x89\x02\n\x1f\x63om.com.terraquantum.bff.v1.bffB\x13RtdCredentialsProtoP\x01Z?terraquantum.swiss/tq42_grpc_client/com/terraquantum/bff/v1/bff\xa2\x02\x05\x43TBVB\xaa\x02\x1b\x43om.Terraquantum.Bff.V1.Bff\xca\x02\x1b\x43om\\Terraquantum\\Bff\\V1\\Bff\xe2\x02\'Com\\Terraquantum\\Bff\\V1\\Bff\\GPBMetadata\xea\x02\x1f\x43om::Terraquantum::Bff::V1::Bffb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.terraquantum.bff.v1.bff.rtd_credentials_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.com.terraquantum.bff.v1.bffB\023RtdCredentialsProtoP\001Z?terraquantum.swiss/tq42_grpc_client/com/terraquantum/bff/v1/bff\242\002\005CTBVB\252\002\033Com.Terraquantum.Bff.V1.Bff\312\002\033Com\\Terraquantum\\Bff\\V1\\Bff\342\002\'Com\\Terraquantum\\Bff\\V1\\Bff\\GPBMetadata\352\002\037Com::Terraquantum::Bff::V1::Bff'
  _globals['_RTDCREDENTIALSPROTO']._serialized_start=82
  _globals['_RTDCREDENTIALSPROTO']._serialized_end=159
# @@protoc_insertion_point(module_scope)
