from enum import Enum


class HMD(str, Enum):
    ACERWMR = "acerWmr"
    ARPARA = "arpara"
    ASUSWMR = "asusWmr"
    BIGSCREENBEYOND = "bigscreenbeyond"
    CLOUDXR = "cloudxr"
    CONTROLLABLE = "controllable"
    DELLVISOR = "dellVisor"
    DISCO = "disco"
    E3 = "e3"
    E4 = "e4"
    GLASSES20 = "glasses20"
    HEDY = "hedy"
    HPREVERB = "hpReverb"
    HUAWEIVR = "huaweivr"
    HYPEREAL = "hypereal"
    INDEX = "index"
    LENOVOEXPLORER = "lenovoExplorer"
    MEDION = "medion"
    MEGANE1 = "megane1"
    MIRAMAR = "miramar"
    NOLOSONIC = "nolosonic"
    PICONEO2 = "picoNeo2"
    PICONEO3 = "picoNeo3"
    PICONEO4 = "picoNeo4"
    PIMAX5K = "pimax5k"
    PIMAX8K = "pimax8k"
    PIMAXARTISAN = "pimaxArtisan"
    PIMAXCRYSTAL = "pimaxCrystal"
    PSVR2 = "psvr2"
    QIYUDREAM = "qiyuDream"
    QUEST = "quest"
    QUEST2 = "quest2"
    QUEST3 = "quest3"
    QUESTPRO = "questPro"
    RIFT = "rift"
    RIFTS = "riftS"
    SAMSUNGWMR = "samsungWmr"
    UNKNOWN = "unknown"
    VAPOREON = "vaporeon"
    VARJOAERO = "varjoaero"
    VIVE = "vive"
    VIVECOSMOS = "viveCosmos"
    VIVEDVT = "viveDvt"
    VIVEELITE = "viveElite"
    VIVEFOCUS = "viveFocus"
    VIVEPRO = "vivePro"
    VIVEPRO2 = "vivePro2"
    VRIDGE = "vridge"
    WMR = "wmr"

    def __str__(self) -> str:
        return str(self.value)
