# Generated by Django 5.0.6 on 2024-10-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_svm', '0010_remove_softwareproductinstallation_netbox_svm_softwareproductinstallation_resource_and_more'),
        ('tenancy', '0015_contactassignment_rename_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareproductinstallation',
            name='contact',
            field=models.ManyToManyField(blank=True, default=None, related_name='assigned_contact', to='tenancy.contact'),
        ),
    ]
