"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class _Stage:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _StageEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Stage.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    EXPLORE: Stage.ValueType = ...  # 0
    REFINE: Stage.ValueType = ...  # 1
class Stage(_Stage, metaclass=_StageEnumTypeWrapper):
    pass

EXPLORE: Stage.ValueType = ...  # 0
REFINE: Stage.ValueType = ...  # 1
global___Stage = Stage


class SolverFidelityRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SIMULATION_STAGE_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    @property
    def simulation_stage(self) -> global___SimulationStageRequest: ...
    value: builtins.float = ...
    def __init__(self,
        *,
        simulation_stage : typing.Optional[global___SimulationStageRequest] = ...,
        value : builtins.float = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["simulation_stage",b"simulation_stage"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["simulation_stage",b"simulation_stage","value",b"value"]) -> None: ...
global___SolverFidelityRequest = SolverFidelityRequest

class SimulationStageRequest(google.protobuf.message.Message):
    """TODO Replace string with Enum"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SIMULATION_FIELD_NUMBER: builtins.int
    STAGE_FIELD_NUMBER: builtins.int
    simulation: typing.Text = ...
    stage: typing.Text = ...
    def __init__(self,
        *,
        simulation : typing.Text = ...,
        stage : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["simulation",b"simulation","stage",b"stage"]) -> None: ...
global___SimulationStageRequest = SimulationStageRequest

class SolverFidelityResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.float = ...
    def __init__(self,
        *,
        value : builtins.float = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["value",b"value"]) -> None: ...
global___SolverFidelityResponse = SolverFidelityResponse

class SolveExecutionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SIMULATION_ID_FIELD_NUMBER: builtins.int
    STAGE_FIELD_NUMBER: builtins.int
    EXECUTE_REMOTELY_FIELD_NUMBER: builtins.int
    simulation_id: typing.Text = ...
    stage: global___Stage.ValueType = ...
    execute_remotely: builtins.bool = ...
    def __init__(self,
        *,
        simulation_id : typing.Text = ...,
        stage : global___Stage.ValueType = ...,
        execute_remotely : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["execute_remotely",b"execute_remotely","simulation_id",b"simulation_id","stage",b"stage"]) -> None: ...
global___SolveExecutionRequest = SolveExecutionRequest

class SolveExecutionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool = ...
    message: typing.Text = ...
    def __init__(self,
        *,
        success : builtins.bool = ...,
        message : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message",b"message","success",b"success"]) -> None: ...
global___SolveExecutionResponse = SolveExecutionResponse
