from volttron.client.messaging import topics as t

VALUE_RESPONSE_PREFIX = t.ACTUATOR_VALUE()
REVERT_POINT_RESPONSE_PREFIX = t.ACTUATOR_REVERTED_POINT()
REVERT_DEVICE_RESPONSE_PREFIX = t.ACTUATOR_REVERTED_DEVICE()
ERROR_RESPONSE_PREFIX = t.ACTUATOR_ERROR()

WRITE_ATTEMPT_PREFIX = t.ACTUATOR_WRITE()

GET_TOPIC = t.ACTUATOR_GET()
RESERVATION_REQUEST_TOPIC = t.ACTUATOR_SCHEDULE_REQUEST()
RESERVATION_RESULT_TOPIC = t.ACTUATOR_SCHEDULE_RESULT()
REVERT_DEVICE_TOPIC = t.ACTUATOR_REVERT_DEVICE()
REVERT_POINT_TOPIC = t.ACTUATOR_REVERT_POINT()
SET_TOPIC = t.ACTUATOR_SET()

RESERVATION_ACTION_NEW = 'NEW_RESERVATION'
RESERVATION_ACTION_CANCEL = 'CANCEL_RESERVATION'
LEGACY_RESERVATION_ACTION_NEW = 'NEW_SCHEDULE'
LEGACY_RESERVATION_ACTION_CANCEL = 'CANCEL_SCHEDULE'

RESERVATION_RESPONSE_SUCCESS = 'SUCCESS'
RESERVATION_RESPONSE_FAILURE = 'FAILURE'

RESERVATION_CANCEL_PREEMPTED = 'PREEMPTED'

ACTUATOR_COLLECTION = 'actuators'