
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-08T10:33:26+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "348ddb1b6de2e182b4211b9918a67ddbe758822a",
 "version": "2.5.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
