# coding: utf-8

"""
    spacestudio satellite API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacestudio_satellite_client.models.timeline_slot import TimelineSlot

class TestTimelineSlot(unittest.TestCase):
    """TimelineSlot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimelineSlot:
        """Test TimelineSlot
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimelineSlot`
        """
        model = TimelineSlot()
        if include_optional:
            return TimelineSlot(
                type = 'ORBIT',
                id = '',
                validity = 'VALID'
            )
        else:
            return TimelineSlot(
        )
        """

    def testTimelineSlot(self):
        """Test TimelineSlot"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
