# coding: utf-8

"""
    spacestudio satellite API documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacestudio_satellite_client.api.platforms_api import PlatformsApi


class TestPlatformsApi(unittest.TestCase):
    """PlatformsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlatformsApi()

    def tearDown(self) -> None:
        pass

    def test_create_platform(self) -> None:
        """Test case for create_platform

        CreatePlatform
        """
        pass

    def test_delete_platform(self) -> None:
        """Test case for delete_platform

        DeletePlatform
        """
        pass

    def test_delete_platforms(self) -> None:
        """Test case for delete_platforms

        DeletePlatforms
        """
        pass

    def test_get_platforms(self) -> None:
        """Test case for get_platforms

        GetPlatforms
        """
        pass

    def test_update_platform(self) -> None:
        """Test case for update_platform

        UpdatePlatform
        """
        pass


if __name__ == '__main__':
    unittest.main()
