from .rule import Rule as Rule

class TextMateGrammarRepository:
    grammars: dict
    loaded_grammars: dict
    def __init__(self, grammars: list[dict]) -> None: ...
    def get_grammar(self, scope_name: str) -> TextMateGrammar | None: ...
    def get_grammar_by_language(self, languag_id: str) -> TextMateGrammar | None: ...
    def __getitem__(self, key: str) -> dict: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def keys(self): ...
    def values(self): ...
    def items(self): ...

class TextMateGrammar:
    def __init__(
        self, grammar: dict, grammar_repository: TextMateGrammarRepository
    ) -> None: ...
    def parse(self, line: str) -> list[tuple[str, tuple[int, int]]]: ...
