# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from com.terraquantum.bff.v1.bff import rtd_credentials_pb2 as com_dot_terraquantum_dot_bff_dot_v1_dot_bff_dot_rtd__credentials__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class BffConfigServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRtdCredentials = channel.unary_unary(
                '/com.terraquantum.bff.v1.bff.BffConfigService/GetRtdCredentials',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=com_dot_terraquantum_dot_bff_dot_v1_dot_bff_dot_rtd__credentials__pb2.RtdCredentialsProto.FromString,
                _registered_method=True)


class BffConfigServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRtdCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BffConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRtdCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRtdCredentials,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=com_dot_terraquantum_dot_bff_dot_v1_dot_bff_dot_rtd__credentials__pb2.RtdCredentialsProto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.terraquantum.bff.v1.bff.BffConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.terraquantum.bff.v1.bff.BffConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BffConfigService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRtdCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.terraquantum.bff.v1.bff.BffConfigService/GetRtdCredentials',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            com_dot_terraquantum_dot_bff_dot_v1_dot_bff_dot_rtd__credentials__pb2.RtdCredentialsProto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
