# SPDX-FileCopyrightText: 2024-present SIMetrix Technologies Ltd, SIMPLIS Technologies Inc.
#
# SPDX-License-Identifier: SIMetrix and SIMetrix/SIMPLIS End User Licence Agreement
import simetrix.schematic
import simetrix.waveform
from typing import Iterator

class Property:
    def name(self) -> str: ...
    def value(self) -> str: ...
    def setValue(self, value: str) -> str: ...

class Properties:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Property: ...
    def __iter__(self) -> Iterator[Property]: ...
    def add(self, name: str, value: str) -> None: ...
    def add(self, property: Property) -> None: ...
    def contains(self, name: str) -> bool: ...
    def find(self, name: str) -> Property: ...


def currentGraph() -> simetrix.waveform.Graph: ...
def currentSchematic() -> simetrix.schematic.Schematic: ...
def getSchematicFromHandle(handle: int) -> simetrix.schematic.Schematic: ...
def graphs() -> list[simetrix.waveform.Graph]: ...
def openSchematic(path: str) -> simetrix.schematic.Schematic: ...
def schematics() -> list[simetrix.schematic.Schematic]: ...
def selectedGraph() -> simetrix.waveform.Waveform: ...
def _namedMap(name: str) -> map: ...
