# coding: utf-8

"""
    spacestudio satellite demo API documentation

    This API is a demo version of the SpaceStudio Satellite API. It is a simplified version of the SpaceStudio Satellite API, with a limited set of functionalities and a reduced set of endpoints. It is intended to be used for demonstration purposes only.

    The version of the OpenAPI document: 1.0.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacestudio_satellite_demo_client.models.refresh_mode import RefreshMode

class TestRefreshMode(unittest.TestCase):
    """RefreshMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRefreshMode(self):
        """Test RefreshMode"""
        # inst = RefreshMode()

if __name__ == '__main__':
    unittest.main()
