# coding: utf-8

"""
    spacestudio satellite demo API documentation

    This API is a demo version of the SpaceStudio Satellite API. It is a simplified version of the SpaceStudio Satellite API, with a limited set of functionalities and a reduced set of endpoints. It is intended to be used for demonstration purposes only.

    The version of the OpenAPI document: 1.0.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacestudio_satellite_demo_client.models.orbit_phasing import OrbitPhasing

class TestOrbitPhasing(unittest.TestCase):
    """OrbitPhasing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrbitPhasing:
        """Test OrbitPhasing
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrbitPhasing`
        """
        model = OrbitPhasing()
        if include_optional:
            return OrbitPhasing(
                target_mission_duration_for_aol = 1.337,
                target_delta_argument_of_latitude = 1.337,
                target_delta_vmax = 1.337,
                optimization_type = ''
            )
        else:
            return OrbitPhasing(
        )
        """

    def testOrbitPhasing(self):
        """Test OrbitPhasing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
