# coding: utf-8

"""
    spacestudio satellite demo API documentation

    This API is a demo version of the SpaceStudio Satellite API. It is a simplified version of the SpaceStudio Satellite API, with a limited set of functionalities and a reduced set of endpoints. It is intended to be used for demonstration purposes only.

    The version of the OpenAPI document: 1.0.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from spacestudio_satellite_demo_client.api.platforms_api import PlatformsApi


class TestPlatformsApi(unittest.TestCase):
    """PlatformsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlatformsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_platform(self) -> None:
        """Test case for delete_platform

        DeletePlatform
        """
        pass

    def test_delete_platforms(self) -> None:
        """Test case for delete_platforms

        DeletePlatforms
        """
        pass

    def test_get_platforms(self) -> None:
        """Test case for get_platforms

        GetPlatforms
        """
        pass


if __name__ == '__main__':
    unittest.main()
