# Generated by Django 4.1.7 on 2023-04-05 12:55

import dcim.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0084_staging'),
        ('dcim', '0167_module_status'),
        ('ipam', '0064_clear_search_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAConPorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mac', dcim.fields.MACAddressField()),
                ('status', models.CharField(default='unknown', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.device')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.interface')),
                ('ipaddress', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipam.ipaddress')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.vlan')),
            ],
            options={
                'verbose_name_plural': 'MAC and IP on switches ports',
            },
        ),
    ]
