
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-09T00:06:03-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "86bb3f70c8f2835d07a675beeb39b1847e20afe7",
 "version": "2.46.3b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
