
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-08T17:55:59-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1d1b92a79b8972823ae9050d70bf60b7c586aabf",
 "version": "3.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
