from typing import Any

class JSONArray:
    def export(self) -> list[Any]: ...

class JSONElement:
    def export(self) -> Any: ...

class JSONObject:
    def export(self) -> dict[str, Any]: ...

class JSONParser:
    def load(self, file: str) -> JSONArray | JSONElement | JSONObject: ...
    def parse(self, value: bytes) -> JSONArray | JSONElement | JSONObject: ...
    def parse_string(self, value: str) -> JSONArray | JSONElement | JSONObject: ...
