# coding: utf-8

"""
    spacestudio satellite demo API documentation

    This API is a demo version of the SpaceStudio Satellite API. It is a simplified version of the SpaceStudio Satellite API, with a limited set of functionalities and a reduced set of endpoints. It is intended to be used for demonstration purposes only.

    The version of the OpenAPI document: 1.0.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EarthPotentialConfiguration(str, Enum):
    """
    EarthPotentialConfiguration
    """

    """
    allowed enum values
    """
    CUSTOM = 'CUSTOM'
    DEFAULT = 'DEFAULT'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EarthPotentialConfiguration from a JSON string"""
        return cls(json.loads(json_str))


