# coding: utf-8

"""
    spacestudio satellite demo API documentation

    This API is a demo version of the SpaceStudio Satellite API. It is a simplified version of the SpaceStudio Satellite API, with a limited set of functionalities and a reduced set of endpoints. It is intended to be used for demonstration purposes only.

    The version of the OpenAPI document: 1.0.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ThrustArcsPosition(str, Enum):
    """
    ThrustArcsPosition
    """

    """
    allowed enum values
    """
    ASCENDING_AND_DESCENDING_NODES = 'ASCENDING_AND_DESCENDING_NODES'
    ASCENDING_NODE = 'ASCENDING_NODE'
    CUSTOM = 'CUSTOM'
    DESCENDING_NODE = 'DESCENDING_NODE'
    APOGEE_AND_PERIGEE = 'APOGEE_AND_PERIGEE'
    APOGEE = 'APOGEE'
    PERIGEE = 'PERIGEE'
    ASCENDING_AND_DESCENDING_ANTINODES = 'ASCENDING_AND_DESCENDING_ANTINODES'
    ASCENDING_ANTINODE = 'ASCENDING_ANTINODE'
    DESCENDING_ANTINODE = 'DESCENDING_ANTINODE'
    MEAN_LONGITUDE = 'MEAN_LONGITUDE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ThrustArcsPosition from a JSON string"""
        return cls(json.loads(json_str))


