# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/terraquantum/invitation/v1/invitation/list_invitations_request.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'com/terraquantum/invitation/v1/invitation/list_invitations_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.terraquantum.invitation.v1.invitation import invitation_pb2 as com_dot_terraquantum_dot_invitation_dot_v1_dot_invitation_dot_invitation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHcom/terraquantum/invitation/v1/invitation/list_invitations_request.proto\x12)com.terraquantum.invitation.v1.invitation\x1a:com/terraquantum/invitation/v1/invitation/invitation.proto\"\x9b\x01\n\x16ListInvitationsRequest\x12\'\n\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12X\n\x06status\x18\x02 \x01(\x0e\x32@.com.terraquantum.invitation.v1.invitation.InvitationStatusProtoR\x06statusB\xe5\x02\n-com.com.terraquantum.invitation.v1.invitationB\x1bListInvitationsRequestProtoP\x01ZMterraquantum.swiss/tq42_grpc_client/com/terraquantum/invitation/v1/invitation\xa2\x02\x05\x43TIVI\xaa\x02)Com.Terraquantum.Invitation.V1.Invitation\xca\x02)Com\\Terraquantum\\Invitation\\V1\\Invitation\xe2\x02\x35\x43om\\Terraquantum\\Invitation\\V1\\Invitation\\GPBMetadata\xea\x02-Com::Terraquantum::Invitation::V1::Invitationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.terraquantum.invitation.v1.invitation.list_invitations_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n-com.com.terraquantum.invitation.v1.invitationB\033ListInvitationsRequestProtoP\001ZMterraquantum.swiss/tq42_grpc_client/com/terraquantum/invitation/v1/invitation\242\002\005CTIVI\252\002)Com.Terraquantum.Invitation.V1.Invitation\312\002)Com\\Terraquantum\\Invitation\\V1\\Invitation\342\0025Com\\Terraquantum\\Invitation\\V1\\Invitation\\GPBMetadata\352\002-Com::Terraquantum::Invitation::V1::Invitation'
  _globals['_LISTINVITATIONSREQUEST']._serialized_start=180
  _globals['_LISTINVITATIONSREQUEST']._serialized_end=335
# @@protoc_insertion_point(module_scope)
