import gspread
import pandas as pd
from _typeshed import Incomplete
from strideutils.stride_config import config as config
from typing import Any

SCOPES: Incomplete

def get_auth(scopes: tuple[str, ...] = ..., service: str = 'sheets', version: str = 'v4'): ...
def grab_sheet(sheet_id: str, sheet_name: str, columns_labeled: bool = True, worksheet: gspread.Worksheet | None = None, scopes: tuple[str, ...] = ..., _cache: dict[str, Any] = {}) -> pd.DataFrame: ...
def write_sheet(df: pd.DataFrame, sheet_id: str, sheet_name: str, worksheet: gspread.Worksheet | None = None, scopes: tuple[str, ...] = ...): ...
def reorder_sheet(sheet_id: str, sheet_name: str, new_location: int = 0, scopes: tuple[str, ...] = ...): ...
def get_sheet_names(sheet_id: str, scopes: tuple[str, ...] = ...) -> list[str]: ...
