# Generated by Django 4.2.16 on 2024-09-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('debug', models.BooleanField(default=False)),
                ('refresh_synergy_frames', models.BooleanField(default=False)),
                ('create_oneview_server_devices', models.BooleanField(default=False)),
                ('create_oneview_server_modules', models.BooleanField(default=False)),
                ('create_oneview_server_interfaces', models.BooleanField(default=False)),
                ('import_nautobot_types', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
