from .services.team_service import TeamService
from .services.fixture_service import FixtureService
from .services.xgoals_service import XGoalsService
from .services.fixture_stats_service import FixtureStatsService
from .services.lineups_service import LineupsService
from .services.injuries_service import InjuriesService
from .services.team_ratings_service import TeamRatingsService
from .services.odds_service import OddsService
from .services.team_stats_service import TeamStatsService

from .models.fixture import TeamService
from .models.fixture_stats import FixtureService
from .models.injury import XGoalsService
from .models.team import FixtureStatsService
from .models.lineups import LineupsService
from .models.te import InjuriesService
from .models.team_ratings_service import TeamRatingsService
from .models.odds_service import OddsService
from .models.team_stats_service import TeamStatsService
