# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/terraquantum/user/v1/waiting_user/get_waiting_user_request.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'com/terraquantum/user/v1/waiting_user/get_waiting_user_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.terraquantum.javalibs.logging.v1 import logging_extensions_pb2 as com_dot_terraquantum_dot_javalibs_dot_logging_dot_v1_dot_logging__extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDcom/terraquantum/user/v1/waiting_user/get_waiting_user_request.proto\x12%com.terraquantum.user.v1.waiting_user\x1a=com/terraquantum/javalibs/logging/v1/logging_extensions.proto\"K\n\x15GetWaitingUserRequest\x12\x32\n\x05\x65mail\x18\x01 \x01(\tB\x1c\x88\xb5\x18\x01\xa2\xb5\x18\x14^[^@]{3}(.*)(\\.\\w+)$R\x05\x65mailB\xc8\x02\n)com.com.terraquantum.user.v1.waiting_userB\x1aGetWaitingUserRequestProtoP\x01ZIterraquantum.swiss/tq42_grpc_client/com/terraquantum/user/v1/waiting_user\xa2\x02\x05\x43TUVW\xaa\x02$Com.Terraquantum.User.V1.WaitingUser\xca\x02$Com\\Terraquantum\\User\\V1\\WaitingUser\xe2\x02\x30\x43om\\Terraquantum\\User\\V1\\WaitingUser\\GPBMetadata\xea\x02(Com::Terraquantum::User::V1::WaitingUserb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.terraquantum.user.v1.waiting_user.get_waiting_user_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n)com.com.terraquantum.user.v1.waiting_userB\032GetWaitingUserRequestProtoP\001ZIterraquantum.swiss/tq42_grpc_client/com/terraquantum/user/v1/waiting_user\242\002\005CTUVW\252\002$Com.Terraquantum.User.V1.WaitingUser\312\002$Com\\Terraquantum\\User\\V1\\WaitingUser\342\0020Com\\Terraquantum\\User\\V1\\WaitingUser\\GPBMetadata\352\002(Com::Terraquantum::User::V1::WaitingUser'
  _globals['_GETWAITINGUSERREQUEST'].fields_by_name['email']._loaded_options = None
  _globals['_GETWAITINGUSERREQUEST'].fields_by_name['email']._serialized_options = b'\210\265\030\001\242\265\030\024^[^@]{3}(.*)(\\.\\w+)$'
  _globals['_GETWAITINGUSERREQUEST']._serialized_start=174
  _globals['_GETWAITINGUSERREQUEST']._serialized_end=249
# @@protoc_insertion_point(module_scope)
