# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: ${GITHUB_REF_NAME:1}
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chris_oag.api.userfiles_api import UserfilesApi


class TestUserfilesApi(unittest.TestCase):
    """UserfilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserfilesApi()

    def tearDown(self) -> None:
        pass

    def test_userfiles_create(self) -> None:
        """Test case for userfiles_create

        """
        pass

    def test_userfiles_destroy(self) -> None:
        """Test case for userfiles_destroy

        """
        pass

    def test_userfiles_list(self) -> None:
        """Test case for userfiles_list

        """
        pass

    def test_userfiles_retrieve(self) -> None:
        """Test case for userfiles_retrieve

        """
        pass

    def test_userfiles_retrieve_0(self) -> None:
        """Test case for userfiles_retrieve_0

        """
        pass

    def test_userfiles_search_list(self) -> None:
        """Test case for userfiles_search_list

        """
        pass

    def test_userfiles_update(self) -> None:
        """Test case for userfiles_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
