from enum import Enum

class URL(Enum):
    account_login = "/db/accounts/loginGJAccount.php"
    account_register = "/db/accounts/registerGJAccount.php"
    get_scores = "/db/getGJScores.php"
    get_levels = "/db/getGJLevels.php"
    level_download = "/db/downloadGJLevel.php"
    account_comment_get = "/db/getGJAccountComments20.php"
    get_user_info = "/db/getGJUserInfo20.php"

    friend_accept_request = "/db/acceptGJFriendRequest20.php"
    friend_get_requests = "/db/getGJFriendRequests20.php"
    friend_read_request = "/db/readGJFriendRequest20.php"
    friend_reject_request = "/db/deleteGJFriendRequests20.php"
    friend_request = "/db/uploadFriendRequest20.php"
    friend_remove = "/db/removeGJFriend20.php"
    unblock_user = "/db/unblockGJUser20.php"
    block_user = "/db/blockGJUser20.php"

    get_challenges = "/db/getGJChallenges.php"
    comment_get_history = "/db/getGJCommentHistory.php"
    comments_get = "/db/getGJComments21.php"

    account_sync_new = "/db/accounts/syncGJAccount20.php"
    account_sync = "/db/accounts/syncGJAccount.php"
    account_backup_new = "/db/database/accounts/backupGJAccountNew.php"
    account_backup = "/db/accounts/backupGJAccount.php"

    account_comment_delete = "/db/deleteGJAccComment20.php"
    comment_delete = "/db/deleteGJComment20.php"
    level_delete = "/db/deleteGJLevelUser20.php"
    message_delete = "/db/deleteGJMessages20.php"
    message_get = "/db/downloadGJMessage20.php"
    get_creators = "/db/getGJCreators.php"
    level_get_daily = "/db/getGJDailyLevel.php"
    get_gauntlets = "/db/getGJGauntlets.php"
    get_level_scores = "/db/getGJLevelScores.php"
    get_map_packs = "/db/getGJMapPacks.php"
    message_get_all = "/db/getGJMessages20.php"
    get_rewards = "/db/getGJRewards.php"
    get_song_info = "/db/getGJSongInfo.php"
    get_top_artists = "/db/getGJTopArtists.php"
    get_user_list = "/db/getGJUserList20.php"
    get_users = "/db/getGJUsers20.php"
    like_item = "/db/likeGJItem.php"
    rate_demon = "/db/rateGJDemon21.php"
    rate_star = "/db/rateGJStars20.php"
    level_report = "/db/reportGJLevel.php"
    request_mod = "/db/requestUserAccess.php"
    suggest_stars = "/db/suggestGJStars20.php"
    update_account_settings = "/db/updateGJAccSettings20.php"
    level_update_description = "/db/updateGJDesc20.php"
    update_user_score = "/db/updateGJUserScore.php"
    account_comment_upload = "/db/uploadGJAccComment20.php"
    comment_upload = "/db/uploadGJComment.php"
    level_upload = "/db/uploadGJLevel.php"
    message_upload = "/db/uploadGJMessage20.php"
    level_list_delete = "/db/deleteGJLevelList.php"
    level_list_upload = "/db/uploadGJLevelList.php"
    level_list_search = "/db/getGJLevelLists.php"
    get_level_plat_scores = "/db/getGJLevelScoresPlat.php"
    relay_sfx = "/db/content/sfx/{sfxid}"
    get_music_library = "/db/content/music/musiclibrary.dat"
    get_music_library_version = "/db/content/music/musiclibrary_version.txt"
    get_song_info_mp3 = "/db/mp3"