
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-08T15:01:30+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "8a2f586379ca2466b85c7e687755a88fda414768",
 "version": "0.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
