# SPDX-FileCopyrightText: 2024-present SIMetrix Technologies Ltd, SIMPLIS Technologies Inc.
#
# SPDX-License-Identifier: SIMetrix and SIMetrix/SIMPLIS End User Licence Agreement
import typing
import simetrix

class AbstractSchematicObject:
    def handle(self) -> str: ...
    def hasProperty(self, name: str) -> bool: ...
    def properties(self) -> simetrix.Properties: ...
    def propertyNames(self) -> list[str]: ...
    def propertyValue(self, name: str) -> str: ...
    def schematic(self) -> str: ...
    def setProperty(self, name: str, value: str) -> None: ...

class Instance(AbstractSchematicObject):
    def symbolName(self) -> str: ...

class Schematic:
    def handle(self) -> str: ...
    def hasProperty(self, name: str) -> bool: ...
    def instance(self, handle: str) -> Instance: ...
    def instances(self) -> list[Instance]: ...
    def propertyValue(self, name: str) -> str: ...
    def select(self) -> None: ...
    def setProperty(self, name: str, value: str) -> None: ...
    
