
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-07T22:49:51-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "cbcff6c5b01a6037d8fba1a4ef845a3258d2be57",
 "version": "0.34.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
