from .services.team_service import TeamService
from .services.fixture_service import FixtureService
from .services.xgoals_service import XGoalsService
from .services.fixture_stats_service import FixtureStatsService
from .services.lineups_service import LineupsService
from .services.injury_service import InjuriesService
from .services.team_ratings_service import TeamRatingsService
from .services.odds_service import OddsService
from .services.team_stats_service import TeamStatsService
