# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: ${GITHUB_REF_NAME:1}
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chris_oag.api.chris_admin_api import ChrisAdminApi


class TestChrisAdminApi(unittest.TestCase):
    """ChrisAdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChrisAdminApi()

    def tearDown(self) -> None:
        pass

    def test_chris_admin_api_v1_computeresources_create(self) -> None:
        """Test case for chris_admin_api_v1_computeresources_create

        """
        pass

    def test_chris_admin_api_v1_computeresources_destroy(self) -> None:
        """Test case for chris_admin_api_v1_computeresources_destroy

        """
        pass

    def test_chris_admin_api_v1_computeresources_list(self) -> None:
        """Test case for chris_admin_api_v1_computeresources_list

        """
        pass

    def test_chris_admin_api_v1_computeresources_retrieve(self) -> None:
        """Test case for chris_admin_api_v1_computeresources_retrieve

        """
        pass

    def test_chris_admin_api_v1_create(self) -> None:
        """Test case for chris_admin_api_v1_create

        """
        pass

    def test_chris_admin_api_v1_destroy(self) -> None:
        """Test case for chris_admin_api_v1_destroy

        """
        pass

    def test_chris_admin_api_v1_list(self) -> None:
        """Test case for chris_admin_api_v1_list

        """
        pass

    def test_chris_admin_api_v1_retrieve(self) -> None:
        """Test case for chris_admin_api_v1_retrieve

        """
        pass

    def test_chris_admin_api_v1_update(self) -> None:
        """Test case for chris_admin_api_v1_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
