# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: ${GITHUB_REF_NAME:1}
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chris_oag.api.groups_api import GroupsApi


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupsApi()

    def tearDown(self) -> None:
        pass

    def test_groups_create(self) -> None:
        """Test case for groups_create

        """
        pass

    def test_groups_destroy(self) -> None:
        """Test case for groups_destroy

        """
        pass

    def test_groups_list(self) -> None:
        """Test case for groups_list

        """
        pass

    def test_groups_retrieve(self) -> None:
        """Test case for groups_retrieve

        """
        pass

    def test_groups_search_list(self) -> None:
        """Test case for groups_search_list

        """
        pass

    def test_groups_users_create(self) -> None:
        """Test case for groups_users_create

        """
        pass

    def test_groups_users_destroy(self) -> None:
        """Test case for groups_users_destroy

        """
        pass

    def test_groups_users_list(self) -> None:
        """Test case for groups_users_list

        """
        pass

    def test_groups_users_retrieve(self) -> None:
        """Test case for groups_users_retrieve

        """
        pass

    def test_groups_users_search_list(self) -> None:
        """Test case for groups_users_search_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
