# coding: utf-8

"""
    ChRIS Research Integration System: Ultron BackEnd (CUBE) API

    The ChRIS Ultron BackEnd (CUBE) is the core backend API of ChRIS. It manages ChRIS users, plugins, pipelines, and the provenance of data analyses as ChRIS feeds.

    The version of the OpenAPI document: ${GITHUB_REF_NAME:1}
    Contact: dev@babymri.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chris_oag.api.pipelines_api import PipelinesApi


class TestPipelinesApi(unittest.TestCase):
    """PipelinesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PipelinesApi()

    def tearDown(self) -> None:
        pass

    def test_all_workflows_list(self) -> None:
        """Test case for all_workflows_list

        """
        pass

    def test_pipelines_boolean_parameter_retrieve(self) -> None:
        """Test case for pipelines_boolean_parameter_retrieve

        """
        pass

    def test_pipelines_boolean_parameter_update(self) -> None:
        """Test case for pipelines_boolean_parameter_update

        """
        pass

    def test_pipelines_create(self) -> None:
        """Test case for pipelines_create

        """
        pass

    def test_pipelines_destroy(self) -> None:
        """Test case for pipelines_destroy

        """
        pass

    def test_pipelines_float_parameter_retrieve(self) -> None:
        """Test case for pipelines_float_parameter_retrieve

        """
        pass

    def test_pipelines_float_parameter_update(self) -> None:
        """Test case for pipelines_float_parameter_update

        """
        pass

    def test_pipelines_integer_parameter_retrieve(self) -> None:
        """Test case for pipelines_integer_parameter_retrieve

        """
        pass

    def test_pipelines_integer_parameter_update(self) -> None:
        """Test case for pipelines_integer_parameter_update

        """
        pass

    def test_pipelines_json_retrieve(self) -> None:
        """Test case for pipelines_json_retrieve

        """
        pass

    def test_pipelines_list(self) -> None:
        """Test case for pipelines_list

        """
        pass

    def test_pipelines_parameters_list(self) -> None:
        """Test case for pipelines_parameters_list

        """
        pass

    def test_pipelines_pipings_list(self) -> None:
        """Test case for pipelines_pipings_list

        """
        pass

    def test_pipelines_pipings_retrieve(self) -> None:
        """Test case for pipelines_pipings_retrieve

        """
        pass

    def test_pipelines_plugins_list(self) -> None:
        """Test case for pipelines_plugins_list

        """
        pass

    def test_pipelines_retrieve(self) -> None:
        """Test case for pipelines_retrieve

        """
        pass

    def test_pipelines_search_list(self) -> None:
        """Test case for pipelines_search_list

        """
        pass

    def test_pipelines_sourcefiles_create(self) -> None:
        """Test case for pipelines_sourcefiles_create

        """
        pass

    def test_pipelines_sourcefiles_list(self) -> None:
        """Test case for pipelines_sourcefiles_list

        """
        pass

    def test_pipelines_sourcefiles_retrieve(self) -> None:
        """Test case for pipelines_sourcefiles_retrieve

        """
        pass

    def test_pipelines_sourcefiles_retrieve_0(self) -> None:
        """Test case for pipelines_sourcefiles_retrieve_0

        """
        pass

    def test_pipelines_sourcefiles_search_list(self) -> None:
        """Test case for pipelines_sourcefiles_search_list

        """
        pass

    def test_pipelines_string_parameter_retrieve(self) -> None:
        """Test case for pipelines_string_parameter_retrieve

        """
        pass

    def test_pipelines_string_parameter_update(self) -> None:
        """Test case for pipelines_string_parameter_update

        """
        pass

    def test_pipelines_update(self) -> None:
        """Test case for pipelines_update

        """
        pass

    def test_pipelines_workflows_create(self) -> None:
        """Test case for pipelines_workflows_create

        """
        pass

    def test_pipelines_workflows_destroy(self) -> None:
        """Test case for pipelines_workflows_destroy

        """
        pass

    def test_pipelines_workflows_plugininstances_list(self) -> None:
        """Test case for pipelines_workflows_plugininstances_list

        """
        pass

    def test_pipelines_workflows_retrieve(self) -> None:
        """Test case for pipelines_workflows_retrieve

        """
        pass

    def test_pipelines_workflows_search_list(self) -> None:
        """Test case for pipelines_workflows_search_list

        """
        pass

    def test_pipelines_workflows_update(self) -> None:
        """Test case for pipelines_workflows_update

        """
        pass

    def test_workflows_list(self) -> None:
        """Test case for workflows_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
